# Application Configuration File
# This demonstrates various logger configurations using YAML

# Server configuration
server:
  port: 8083
  name: "viper-config-demo"
  environment: "development"

# Service information
service:
  name: "viper-config-api"
  version: "v1.0.0"
  description: "Viper configuration demo service"

# Logger configuration
logger:
  engine: "slog"              # Engine type: "zap" or "slog"
  level: "debug"              # Log level: "debug", "info", "warn", "error", "fatal"
  format: "json"              # Format: "json" or "console"
  development: true           # Enable development mode
  disable_caller: false       # Disable caller information
  disable_stacktrace: false   # Disable stack trace

  # Output paths - where logs should be written
  output_paths:
    - "stdout"                # Console output
    - "logs/app.log"          # File output


  # OTLP (OpenTelemetry) configuration - now part of logger
  otlp_endpoint: "localhost:4317"
  otlp:
    enabled: true
    endpoint: "localhost:4317"
    protocol: "grpc"          # "grpc" or "http"
    timeout: "10s"
    insecure: true
    headers:
      x-api-key: "demo-key"
      x-environment: "development"